export const STORAGE_KEYS = {
  PETS: '@vetsync:pets',
  PET_ATIVO: '@vetsync:pet_ativo',
  EVENTOS: '@vetsync:eventos',
  ONBOARDING_CONCLUIDO: '@vetsync:onboarding',
  SESSAO: '@vetsync:sessao',
  SESSAO_ENCERRADA: '@vetsync:sessao_encerrada',
  CONTAS_CONHECIDAS: '@vetsync:contas_conhecidas',
  RECOMPENSAS: '@vetsync:recompensas',
  VETERINARIOS: '@vetsync:veterinarios',
  VETERINARIO_ATIVO: '@vetsync:veterinario_ativo',
  DISPONIBILIDADE: '@vetsync:disponibilidade',
  BLOQUEIOS_AGENDA: '@vetsync:bloqueios_agenda',
  PUSH_TOKEN: '@vetsync:push_token',
};
